version: '3'
services:
  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - ./data:/data
    ports:
      - "9010:9000"
      - "9011:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio@pass
    command: server /data --console-address ":9001" --address ":9000"